- .github/workflows/Test.yml
- app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapDetail.kt
- app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
- app/src/main/java/kr/sparta/tripmate/util/method/method.kt
- app/src/main/res/drawable/bodyshape.xml
- app/src/main/res/drawable/scrap_content_outline.xml
- app/src/main/res/drawable/searchview_outline.xml
- app/src/main/res/layout/fragment_scrap.xml
- app/src/main/res/layout/scraptitems.xml
- 해당이슈 링크 없을경우 생략가능
- 수정사항을 최대한 자세하게 적기.
- 적을때에는 내 설명없이 다른사람이 해당글만보고도 내가 어떤작업을 했는지 완벽히 이해할수있겠다싶을정도를 기준으로 작성하기.
- 해당 PR 살펴볼시 참고하면 좋을 사항들을 기록하기.
- 참고사항이 없을경우 기록하지 않아도 무방.
- 내가 개발을 진행하며 참고했던 사이트링크 혹은 해당 구현사항을 파악하는데 도움이 되는 링크
> scrap 페이지 구현

- app/src/main/res/layout/fragment_community.xml
- app/src/main/res/layout/fragment_community_main_item.xml
- app/src/main/res/values/strings.xml
> community main페이지: 디자인 완료

- app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
- #63 
- 설정 페이지에서 로그아웃 기능과 회원탈퇴 기능을 구현했습니다.
- 로그아웃 하거나, 회원 탈퇴를 했을때 로그인 페이지로 이동됩니다.
> setting : 로그아웃&회원탈퇴 기능 구현

- app/src/main/java/kr/sparta/tripmate/domain/model/ScrapModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
- #67 
-  북마크 저장할 때 리스트 형태로 저장해서 인덱스 충돌 오류를 해결 했습니다.
-  경로를 변경했습니다.
-  앱을 재 실행해서 검색했을때 기존에 북마크에 저장되었던 항목과 비교해서 즐겨찾기 표시가 되게 했습니다.
> scrap : firebase 저장

- app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
- app/src/main/res/layout/activity_community_write.xml
- app/src/main/res/layout/fragment_community.xml
- #57 
- 커뮤니티 글쓰기 페이지에서  글제목,내용을 작성하고 공유버튼을 누르면 커뮤니티 메인의 리싸이클러뷰에 표시됩니다. 
- 커뮤니티 글쓰기 페이지에서 공유버튼을 누르면 파이어베이스에저장되고 , 커뮤니티메인프래그먼트에서 불러옵니다. 
- 커뮤니티 모델 클래스에 내용(디테일) 부분을 추가(수정) 하였습니다.
- 커뮤니티 메인 페이지에서 글쓰기 페이지에 진입할 수 있도록 좌상단 커뮤니티(텍스트파일)에 클릭이벤트처리를 해 두었습니다.
- 하드코딩된 부분을 스트링처리를 아직 하지 못했습니다.
- 커뮤니티 글상세페이지 연결이 아직 되지 않았습니다.
> 커뮤니티 게시판에서 글 작성시 리싸이클러뷰에 표시 되게 구현

- app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
- app/src/main/res/layout/activity_community_write.xml
-  레이아웃 id 속성에 공유버튼 아이디가 공유되어 빈뷰를 클릭했을때도 저장되는 버그 수정
> 커뮤니티 작성페이지 버그수정

- app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
- 빈뷰를 클릭했을때 저장되는 이슈를 해결하다가, id 값이 같은줄 착각해 생긴 버그를 수정하였습니다
- id 값이 달라 액티비티에 수정하였습니다.
> 커뮤니티 글쓰기페이지: 버튼id 수정

- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityMyModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityBoardViewModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardViewModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/scrap/HomeScrapFactory.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/scrap/HomeScrapViewModel.kt
- #93 
- Community UI
- 프로필 사진 클릭 시 myPage로 이동됩니다.
- 좋아요를 누르면 숫자가 1 증가하거나 감소합니다.
- 좋아요를 눌렀을때 적용된 숫자를 파이어베이스에 저장합니다.
- 아이템뷰를 롱 클릭하면 데이터베이스에 북마크 저장됩니다.
- 블로그 사진 클릭 시 블로그로 이동됩니다.
- 블로그 사진 클릭 시 views가 1 증가합니다.
- 데이터 관리는 모두 라이브데이터로 관리합니다.
- 
- 기능구현만 했습니다. 리펙토링 예정입니다.
> community : UI&북마크&좋아요&VIEWS 기능 구현

- app/src/main/res/layout/activity_community_detail.xml
#94 
- 디테일 페이지에서 이미지가 업로드 되지 않을때 뷰가 사라지지않던 문제를 수정했습니다.( 빈값이 "" 로 들어오는걸 Null 판정으로 처리하여 문제가 되었었습니다)
- 디테일 페이지에서 프로필 이미지를 써클뷰로 수정하였습니다.
이미지의 빈값 반환이  "" 로 들어오는걸 Null 판정으로 조건문을 처리하여 문제가 되었었습니다 ( 로그켓의 활용과, isNullBlank()의 개념부족)
- 내가 개발을 진행하며 참고했던 사이트링크 혹은 해당 구현사항을 파악하는데 도움이 되는 링크
> 커뮤니티 : 이미지 업로드시 뷰가 사라지지않던 문제수정,디테일페이지 UI 수정

- app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
- app/src/main/java/kr/sparta/tripmate/data/model/community/BoardKeyModel.kt
- app/src/main/java/kr/sparta/tripmate/data/model/community/CommunityModel.kt
- app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseCommunityRepositoryImpl.kt
- app/src/main/java/kr/sparta/tripmate/domain/model/firebase/BoardKeyModelEntity.kt
- app/src/main/java/kr/sparta/tripmate/domain/model/firebase/CommunityModelEntity.kt
- app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseBoardKeyMapper.kt
- app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseCommunityMapper.kt
- app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseCommunityRepository.kt
- app/src/main/java/kr/sparta/tripmate/domain/usecase/GetFirebaseCommunityData.kt
- app/src/main/java/kr/sparta/tripmate/domain/usecase/UpdateCommuBoard.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityBoardViewModel.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityFactory.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
- #104 
-   remote&domain 데이터클래스 추가했습니다.
-  도메인 usecase를 추가했습니다.
-  도메인 레파지토리를 수정했습니다.
-  remote 레파지토리를 수정했습니다.
-  FirebaseDBRemoteDataSource를 수정했습니다.
-  뷰모델&팩토리를 수정했습니다.
-  북마크 식별키를 라이브데이터로 관리하고 RDB에 저장합니다.
-  북마크 여부를 토스트 메시지로 표시합니다.
- 코드변경이 많아서 확인부탁바랍니다.
> Community : 북마크 관련 로직 분리

- app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/home/HomeScrapListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageTabLayoutAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/home_first_items.xml
- #108 
- 기존에 Scrap에서 데이터를 RDB에 추가&제거 할때 Home화면에서는 갱신이 되는데, MyPage에서는 갱신이 안되는 이슈가 있었습니다.
- 뷰페이저어댑터를 이용해서 해당 프래그먼트를 호출해서 갱신하는 방법으로 해결했습니다.
> MyPage에서 북마크된 Scrap데이터 추가&삭제 시 갱신됩니다.

- app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
- app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseBoardRepositoryImpl.kt
- app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseBoardRepository.kt
- app/src/main/java/kr/sparta/tripmate/domain/usecase/GetFirebaseBoardData.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageTabLayoutAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardFactory.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardViewModel.kt
- #109 
- MVVM 코드분리
- RDB에 저장된 Community중에서 내가 쓴 글만 불러와서 앱에 표시합니다.
- RDB에 추가되는 데이터가 앱 화면에 실시간 갱신됩니다.
> MyPage : RDB데이터 앱에 표시& 실시간 갱신

- app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardListAdapter.kt
- #116 
- 좋아요 버튼 수정
- MyPage/Board : 클릭이벤트 추가 (썸네일 클릭 시 intent데이터를 가지고 Community Detail페이지로 넘어갑니다.)
- Community의 어댑터에있던 intent관련 코드를 프래그먼트로 이동했습니다.
- MyPage & Community에서 RDB에 저장된 addedImage가 없다면 기본이미지, 있다면 해당 이미지로 앱에 표시됩니다.
> MyPage & Community UI

- app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
- app/src/main/java/kr/sparta/tripmate/ui/home/HomeBoardListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardFactory.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardViewModel.kt
- #109 
- RDB데이터 중에서 내가 작성한 글이 MyPage 화면에 표시합니다.
- 커뮤니티 데이터 추가했을때 실시간 갱신됩니다.
- Home/Board 데이터 관리를 위해 뷰모델 추가했습니다.
- RDB데이터 중에서 좋아요가 많은 순서대로 Home 화면에 표시하기
> Home : 커뮤니티 RDB데이터 화면에 표시

- app/src/main/AndroidManifest.xml
- app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/userprofile/main/UserProfileActivity.kt
- app/src/main/java/kr/sparta/tripmate/ui/userprofile/main/UserProfileTab.kt
- app/src/main/java/kr/sparta/tripmate/ui/userprofile/main/UserProfileTabLayoutAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/userprofile/model/UserProfileModel.kt
- app/src/main/res/drawable/arrow_left_white.xml
- app/src/main/res/layout/activity_user_profile.xml
- app/src/main/res/layout/fragment_user_profile_board.xml
- app/src/main/res/layout/item_user_profile_board.xml
- app/src/main/res/values/strings.xml
- #115 
UserProfile 페이지 구현완료
- 사용자 프로필 디자인 및 기능구현 완료했습니다.
- 아직 Community부분 작업이 마무리되지않아 item 클릭시 프로필화면으로 이동하는부분은 구현하지 못했습니다.
- Fragment에 해당 유저가 작성한 글목록을 불러오는기능은 추후 구현할 예정입니다.
> UserProfile페이지 : 페이지 구현완료

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values/strings.xml
- build.gradle.kts
- #100 #112 
- 페이스북 로그인을 구현했습니다.
- 페이스북 로그인시, 값은 제대로 들어오지만 이미지는 기본이미지로 표시되는 버그가있습니다( 예전부터 있던 버그고 있었다가 없었다가 한다고 합니다)
- https://stackoverflow.com/questions/49917726/retrieving-default-image-all-url-profile-picture-from-facebook-graph-api
- https://youtu.be/efI0MgZEfKQ?si=kj-CmJj_mSGp2DiY 를 참고했지만 토큰 기재부분이 명확하지 않습니다.
> 로그인: 페이스북 로그인 구현

- app/src/main/AndroidManifest.xml
- app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values/strings.xml
- 페이스북은 사용하지 않기로하여 이전 코드로 롤백 하였습니다.
-
> 로그인: 페이스북 롤백

- app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
- app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseScrapRepositoryImpl.kt
- app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseScrapRepository.kt
- app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasescraprepository/GetFirebaseBoardKeyDataFromScrapRepo.kt
- app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageFactory.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageViewModel.kt
- #135 
- MyPage의 "스크랩 목록"에 북마크된 목록만 표시되게 수정했습니다.
- 북마크된 목록의 추가&제거 했을때 갱신됩니다.
>  스크랩 목록의 RDB데이터 북마크 추가&갱신

- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_my_page.xml
> 마이페이지: 디자인 수정3

- app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
- #169
- 수정사항을 최대한 자세하게 적기.
- 적을때에는 내 설명없이 다른사람이 해당글만보고도 내가 어떤작업을 했는지 완벽히 이해할수있겠다싶을정도를 기준으로 작성하기.
- 게시글을 작성 할 때 제목이없으면 게시글이 작성되지 않았으나, 제목이 없는데 내용이 있으면 게시글이 작성되던 문제를 수정했습니다.
- 제목에 숫자&영어&한글을 제외한 문자를 입력했을때 경고 토스트메시지는 출력되지만 게시글은 작서되던문제를 수정했습니다.
> Community : 게시글 수정&추가 할 때 작성 조건 수정

- app/src/main/res/layout/fragment_home.xml
- 해당이슈 링크 없을경우 생략가능
- 홈 UI 수정
- 해당 PR 살펴볼시 참고하면 좋을 사항들을 기록하기.
- 참고사항이 없을경우 기록하지 않아도 무방.
- 내가 개발을 진행하며 참고했던 사이트링크 혹은 해당 구현사항을 파악하는데 도움이 되는 링크
> <design> 홈화면 UI 수정

- app/src/main/java/kr/sparta/tripmate/data/repository/community/FirebaseBoardRepositoryImpl.kt
- app/src/main/java/kr/sparta/tripmate/domain/repository/community/FirebaseBoardRepository.kt
- app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/GetBoardUseCase.kt
- app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/UpdateBoardUseCase.kt
- app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityViewModel.kt
- #188 
- 검색했을때 제목&내용에 검색어가 포함된 게시글만 화면에 보여줍니다.
- community에서 검색했을떄 정상적으로 작동하는지 한 번 확인 부탁드립니다.
> community : 검색했을때 제목&내용에 검색어가 포함된 게시글만 화면에 보여줍니다.

- app/src/main/java/kr/sparta/tripmate/data/dao/BudgetDao.kt
- app/src/main/java/kr/sparta/tripmate/data/datasource/local/budget/BudgetLocalDataSource.kt
- app/src/main/java/kr/sparta/tripmate/data/repository/budget/BudgetRepositoryImpl.kt
- app/src/main/java/kr/sparta/tripmate/domain/repository/budget/BudgetRepository.kt
- app/src/main/java/kr/sparta/tripmate/domain/usecase/budgetrepository/DeleteAllBudgetsUseCase.kt
- app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingFactory.kt
- app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingViewModel.kt
> 계정탈퇴시 가계부 모두삭제

- app/src/main/java/kr/sparta/tripmate/ui/budget/budgetdetail/procedure/BudgetDetailProcedureListAdapter.kt
- app/src/main/java/kr/sparta/tripmate/ui/budget/budgetdetail/statistics/BudgetDetailStatisticsFragment.kt
- 가계부 과정 price가 음수일경우 소득으로 나오게 수정
- 가계부 통계 소득, 퍼센트 infinity로 나오는거 고침
> 가계부 자잘한 오류 수정
